name: Publish odfe-cli
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Version
        run: |
          TAG_NAME=${GITHUB_REF#refs/*/}
          echo "RELEASE_VERSION=${TAG_NAME:1}" >> $GITHUB_ENV

      - name: Set up Go ubuntu-latest
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: --snapshot --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload macOS(amd64) Artifact
        uses: actions/upload-artifact@v2
        with:
          name: odfe-cli-${{ env.RELEASE_VERSION }}-macOS-amd64
          path: dist/odfe-cli_darwin_amd64/odfe-cli

      - name: Upload Linux(amd64) Artifact
        uses: actions/upload-artifact@v2
        with:
          name: odfe-cli-${{ env.RELEASE_VERSION }}-linux-amd64
          path: dist/odfe-cli_linux_amd64/odfe-cli

      - name: Upload Linux(arm64) Artifact
        uses: actions/upload-artifact@v2
        with:
          name: odfe-cli-${{ env.RELEASE_VERSION }}-linux-arm64
          path: dist/odfe-cli_linux_arm64/odfe-cli

      - name: Upload Windows(i386) Artifact
        uses: actions/upload-artifact@v2
        with:
          name: odfe-cli-${{ env.RELEASE_VERSION }}-windows-386
          path: dist/odfe-cli_windows_386/odfe-cli.exe

      - name: Upload Windows(amd64) Artifact
        uses: actions/upload-artifact@v2
        with:
          name: odfe-cli-${{ env.RELEASE_VERSION }}-windows-amd64
          path: dist/odfe-cli_windows_amd64/odfe-cli.exe
